

import sys, os

def resource_path(relative_path):
    """Devuelve el path correcto tanto si corres .py como .exe"""
    if hasattr(sys, '_MEIPASS'):
        return os.path.join(sys._MEIPASS, relative_path)
    return os.path.join(os.path.abspath("."), relative_path)



STAGE_NAMES = {
    0: "Peachs Castle",
    1: "Sector Z",
    2: "Congo Jungle",
    3: "Planet Zebes",
    4: "Hyrule Castle",
    5: "Yoshis Island",
    6: "Dream Land",
    7: "Saffron City",
    8: "Mushroom Kingdom",
    9: "Dream Land Beta 1",
    10: "Dream Land Beta 2",
    11: "How To Play",
    12: "Mini Yoshis Island",
    13: "Meta Crystal",
    14: "Duel Zone",
    15: "Race To The Finish",
    16: "Final Destination",
    17: "BTT Mario",
    18: "BTT Fox",
    19: "BTT Donkey Kong",
    20: "BTT Samus",
    21: "BTT Luigi",
    22: "BTT Link",
    23: "BTT Yoshi",
    24: "BTT Falcon",
    25: "BTT Kirby",
    26: "BTT Pikachu",
    27: "BTT Jigglypuff",
    28: "BTT Ness",
    29: "BTP Mario",
    30: "BTP Fox",
    31: "BTP Donkey Kong",
    32: "BTP Samus",
    33: "BTP Luigi",
    34: "BTP Link",
    35: "BTP Yoshi",
    36: "BTP Falcon",
    37: "BTP Kirby",
    38: "BTP Pikachu",
    39: "BTP Jigglypuff",
    40: "BTP Ness",
    41: "Deku Tree",
    42: "First Destination",
    43: "Ganons Tower",
    44: "Gym Leader Castle",
    45: "Pokemon Stadium",
    46: "Taltal",
    47: "Glacial",
    48: "Warioware",
    49: "Battlefield",
    50: "Flat Zone",
    51: "Dr Mario",
    52: "Coolcool",
    53: "Dragonking",
    54: "Great Bay",
    55: "Frays Stage",
    56: "Toh",
    57: "Fod",
    58: "Muda",
    59: "Mementos",
    60: "Showdown",
    61: "Spiralm",
    62: "N64",
    63: "Mute DL",
    64: "Madmm",
    65: "Smbbf",
    66: "Smbo",
    67: "Bowserb",
    68: "Peach2",
    69: "Delfino",
    70: "Corneria2",
    71: "Kitchen",
    72: "Blue",
    73: "Onett",
    74: "Zlanding",
    75: "Frosty",
    76: "Smashville2",
    77: "BTT Drm",
    78: "BTT Gnd",
    79: "BTT Yl",
    80: "Battlefield DL",
    81: "BTT Ds",
    82: "BTT Stg1",
    83: "BTT Falco",
    84: "BTT Wario",
    85: "Htemple",
    86: "BTT Lucas",
    87: "BTP Gnd",
    88: "NPC",
    89: "BTP Ds",
    90: "Smashketball",
    91: "BTP Drm",
    92: "Norfair",
    93: "Corneriacity",
    94: "Falls",
    95: "Osohe",
    96: "Yoshi Story 2",
    97: "World1",
    98: "Flat Zone 2",
    99: "Gerudo",
    100: "BTP Yl",
    101: "BTP Falco",
    102: "BTP Poly",
    103: "Hcastle DL",
    104: "Hcastle O",
    105: "Congoj DL",
    106: "Congoj O",
    107: "Pcastle DL",
    108: "Pcastle O",
    109: "BTP Wario",
    110: "Frays Stage Night",
    111: "Goomba Road",
    112: "BTP Lucas2",
    113: "Sector Z DL",
    114: "Saffron DL",
    115: "Yoshi Island DL",
    116: "Zebes DL",
    117: "Sector Z O",
    118: "Saffron O",
    119: "Yoshi Island O",
    120: "Dream Land O",
    121: "Zebes O",
    122: "BTT Bowser",
    123: "BTP Bowser",
    124: "Bowsers Keep",
    125: "Rith Essa",
    126: "Venom",
    127: "BTT Wolf",
    128: "BTP Wolf",
    129: "BTT Conker",
    130: "BTP Conker",
    131: "Windy",
    132: "Data",
    133: "Clancer",
    134: "Japes",
    135: "BTT Marth",
    136: "Gb Land",
    137: "BTT Mtwo",
    138: "BTP Marth",
    139: "Rest",
    140: "BTP Mtwo",
    141: "Csiege",
    142: "Yoshis Island II",
    143: "Final Destination DL",
    144: "Final Destination Tent",
    145: "Coolcool Remix",
    146: "Duel Zone DL",
    147: "Coolcool DL",
    148: "Meta Crystal DL",
    149: "Dream Land SR",
    150: "Pcastle Beta",
    151: "Hcastle Remix",
    152: "Sector Z Remix",
    153: "Mute",
    154: "HRC",
    155: "MK Remix",
    156: "GHZ",
    157: "Subcon",
    158: "Pirate",
    159: "Casino",
    160: "BTT Sonic",
    161: "BTP Sonic",
    162: "Mmadness",
    163: "Rainbowroad",
    164: "Pokemon Stadium 2",
    165: "Norfair Remix",
    166: "Toadsturnpike",
    167: "Taltal Remix",
    168: "BTP Sheik",
    169: "Winter DL",
    170: "BTT Sheik",
    171: "Glacial Remix",
    172: "BTT Marina",
    173: "Dragonking Remix",
    174: "BTP Marina",
    175: "BTT Dedede",
    176: "Draculas Castle",
    177: "Inverted Castle",
    178: "BTP Dedede",
    179: "Mt Dedede",
    180: "Edo",
    181: "Deku Tree DL",
    182: "Zlanding DL",
    183: "BTT Goemon",
    184: "First Remix",
    185: "BTP Goemon",
    186: "Twilight City",
    187: "Melrode",
    188: "Meta Remix",
    189: "Remix RTTF",
    190: "Reapers",
    191: "Scuttle Town",
    192: "Big Boos Haunt",
    193: "Yoshis Island Melee",
    194: "BTT Banjo",
    195: "Spawned Fear",
    196: "Smashville Remix",
    197: "BTP Banjo",
    198: "Pokefloats",
    199: "Big Snowman",
    222: "Random"
}

CHARACTER_IMAGES = {
    0: "mario.png",
    1: "fox.png",
    2: "donkey_kong.png",
    3: "samus.png",
    4: "luigi.png",
    5: "link.png",
    6: "yoshi.png",
    7: "captain_falcon.png",
    8: "kirby.png",
    9: "pikachu.png",
    10: "jigglypuff.png",
    11: "ness.png",
    
    # Nuevos personajes
    29: "falco.png",
    30: "ganondorf.png",       # GND
    31: "young_link.png",      # YLINK
    32: "dr_mario.png",        # DRM
    33: "wario.png",
    34: "dark_samus.png",      # DSAMUS
    35: "link.png",            # ELINK (usamos link.png)
    36: "samus.png",           # J Samus
    37: "ness.png",            # J Ness
    38: "lucas.png",
    39: "link.png",            # J Link
    40: "captain_falcon.png",  # J Falcon
    41: "fox.png",             # J Fox
    42: "mario.png",           # J Mario
    43: "luigi.png",           # J Luigi
    44: "donkey_kong.png",     # J DK
    45: "pikachu.png",         # E Pikachu
    46: "jigglypuff.png",      # J Jigglypuff
    47: "jigglypuff.png",      # E Jigglypuff
    48: "kirby.png",           # J Kirby
    49: "yoshi.png",           # J Yoshi
    50: "pikachu.png",         # J Pikachu
    51: "samus.png",           # E Samus
    52: "bowser.png",
    53: "giga_bowser.png",     # GBOWSER
    54: "mad_piano.png",       # Piano
    55: "wolf.png",
    56: "conker.png",
    57: "mewtwo.png",          # MTWO
    58: "marth.png",
    59: "sonic.png",
    60: "random.png",          # Sandbag (no hay imagen específica)
    61: "super_sonic.png",     # SSONIC
    62: "sheik.png",
    63: "marina.png",
    64: "dedede.png",          # DEDEDE
    65: "goemon.png",
    66: "peppy.png",
    67: "slippy.png",
    68: "banjo.png",           # BANJO
    69: "metal_luigi.png",     # MLUIGI
    70: "ebisumaru.png",
    71: "dragon_king.png",     # DRAGONKING
    
    # Especial
    222: "random.png"          # Random
}

REMIX_MUSIC = {
    47: "Ganondorf Battle",
    48: "Corneria",
    49: "Kokiri Forest",
    50: "Fever",
    51: "Game Corner",
    52: "Town Hall and Tom Nook's Store",
    53: "Stonecarving City",
    54: "Final Destination (Melee)",
    55: "Cool, Cool Mountain",
    56: "Ballad of the Goddess",
    57: "Saria's Song",
    58: "Luna Ascension",
    59: "Gourmet Race (Melee)",
    60: "Muda Kingdom",
    61: "Last Surprise",
    62: "Spiral Mountain",
    63: "Dire, Dire Docks",
    64: "Mute City",
    65: "Battlefield",
    66: "Mad Monster Mansion",
    71: "Melee Menu",
    72: "Green Greens",
    73: "Brinstar Depths (Melee)",
    74: "Koopa's Theme",
    75: "Trainer Battle",
    76: "Koopa's Road",
    77: "Ultimate Koopa",
    78: "Super Mario Bros. 3 (Melee)",
    79: "Delfino Plaza",
    80: "Vs. Klungo",
    81: "Big Blue",
    83: "Onett",
    84: "Upper Brinstar",
    85: "Frosty Village",
    86: "Easton Kingdom",
    87: "Wing Cap",
    88: "Gym Leader Battle",
    89: "Wario Land",
    90: "River Stage",
    91: "DK Rap",
    93: "Mach Rider (Melee)",
    94: "Red & Blue Medley",
    95: "Gerudo Valley",
    96: "Pop Star",
    97: "Star Wolf",
    98: "Starring Wario!",
    100: "Champion Battle",
    101: "Title Theme (Wild World)",
    102: "Temple Theme (Melee)",
    103: "Pollyanna (Melee)",
    104: "Samba de Combo",
    105: "DCMC Performance",
    106: "Unfounded Revenge",
    107: "The Days When My Mother Was There",
    108: "Brawl Menu",
    109: "Team Select",
    110: "Call Me Jr.",
    111: "Clock Tower",
    112: "Bein' Friends",
    113: "Go K.K. Rider!",
    114: "Snakey Chantey",
    115: "Mom's Hometown",
    116: "Flat Zone",
    117: "Flat Zone II",
    118: "Yoshi's Island (Mario Golf)",
    119: "Great Temple/Dark Link",
    120: "Obstacle Course",
    121: "Even Drier Guys",
    122: "Feel Our Pain (Fire Field)",
    123: "Princess Peach's Castle (Melee)",
    124: "Main Theme",
    126: "Multi-Man Melee",
    127: "Cruel Multi-Man Mode",
    128: "Gang-Plank Galleon",
    129: "Final Destination (Brawl)",
    130: "Astral Observatory",
    131: "Aria of the Soul",
    132: "Battle Fanfare",
    133: "King of the Koopas",
    134: "Mr. Patch",
    135: "K. Rool's Acid Punk",
    136: "Beware the Forest's Mushrooms",
    137: "Fight Against Bowser",
    138: "Boss Challenges",
    139: "Crescent Island",
    141: "Rith Essa",
    142: "Targets!",
    143: "Venom",
    144: "Surprise Attack",
    145: "Final Battle",
    147: "Ole!",
    148: "Windy and Co.",
    149: "Star Fox Medley (Melee)",
    150: "dataDyne Central: Defection",
    151: "dataDyne Central: Investigation X",
    152: "Antenna Cradle",
    153: "Mischief Makers Title Theme",
    154: "Esperance",
    155: "Sloprano",
    157: "Overworld Theme",
    158: "Jungle Japes (Melee)",
    159: "Forest Interlude",
    160: "Toad's Turnpike",
    161: "Game Boy Medley",
    167: "Fire Emblem Medley",
    168: "Yoshi's Tale",
    169: "Flower Garden",
    170: "Wildlands",
    171: "Vs. Marx",
    173: "S.S. Aqua",
    174: "Metal Battle",
    175: "Slider",
    176: "Multi-Man Melee 2",
    177: "Together We Ride (Melee)",
    178: "Kanto Wild Pokemon Battle",
    179: "Super Mario Bros. 2 Overworld",
    180: "Pirate Land",
    181: "Yoshi's Tropical Island",
    182: "Flying Battery",
    183: "Open Your Heart",
    184: "Sonic 2 Boss",
    186: "Casino Night Zone",
    187: "Monkey Watch",
    188: "Sonic 2 Special Stage",
    189: "Sonic CD Special Stage",
    190: "Giant Wing",
    191: "Emerald Hill Zone",
    192: "Live and Learn",
    193: "Stardust Speedway B Mix",
    194: "Green Hill Zone",
    195: "Chemical Plant Zone",
    196: "Baby Bowser",
    197: "Ocean Medley",
    198: "Metallic Madness",
    199: "Everything (Super Sonic)",
    200: "Rock Solid",
    201: "Rainbow Road",
    202: "Victory Lap",
    203: "Raceways",
    204: "Link's Awakening Medley",
    205: "Corridors of Time",
    206: "Kirby 64 Boss",
    207: "Waluigi Pinball",
    211: "Super Mario Bros. 2 Medley",
    212: "Super Mario World Title/Credits",
    213: "Dragon King",
    214: "King Dedede's Theme",
    215: "Dracula's Castle",
    216: "Iron-Blue Intention",
    217: "Dracula's Tears",
    218: "WarioWare, Inc.",
    219: "Bloody Tears",
    220: "Frozen Hillside",
    221: "Meta Knight's Revenge",
    222: "Main Menu",
    223: "Trouble Maker",
    224: "Menu 2 (Melee)",
    225: "Perfect!",
    226: "Control Center",
    227: "Edo Castle Medley",
    228: "In The Final",
    230: "Middle Boss Battle",
    231: "Q Watch (Pause Menu)",
    232: "Kai Highway",
    233: "Athletic Theme",
    234: "Crateria Surface",
    235: "Rainbow Road (SNES)",
    236: "Ocarina of Time Medley",
    237: "Boss E",
    238: "Marine Fortress",
    239: "Twilight City",
    240: "Southern Island/Main Theme",
    241: "Battle Theme",
    242: "Gorgeous Musical Castle",
    243: "Decisive",
    244: "Battlefield Ver. 2",
    245: "Bob-omb Battlefield",
    246: "Area 6",
    247: "Hilltop Chase",
    248: "Status",
    249: "Boss Encounter",
    250: "Grim Reaper's Cavern",
    251: "Shitto Kai / World of Envy",
    252: "Day/Night Traveling",
    253: "Burning Town",
    254: "Boss Battle (Shantae)",
    255: "Fortress Boss",
    0: "Horror Land",
    1: "Title Theme",
    2: "Dark World",
    6: "Menu (Blast Corps)",
    7: "Frappe Snowland",
    8: "Fight Against Monsters",
    9: "Traveling",
    10: "Chill",
    11: "Roll's Theme",
    12: "Stickerbrush Symphony",
    13: "DOOM Medley",
    14: "Running From Evil",
    16: "Grabbag",
    17: "With Mila's Divine Protection",
    18: "Opening (Donkey Kong)",
    19: "Plantation",
    20: "Gold & Silver Medley",
    21: "Haunted House",
    23: "7AM",
    26: "Que Que",
    28: "Goldenrod City",
    29: "Clock Town",
    30: "Bumper Crop Bump",
    31: "Vs. Ridley",
    32: "Ganon Battle Medley",
    33: "Little Fugue",
    34: "Nutty Noon",
    35: "Ghost Gulping",
    37: "Climb Up! And Get the Last Chance!",
    38: "Character Select (Jet Force Gemini)",
    39: "Yoshi's Song",
    40: "Board Shop",
    41: "U.N. Owen Was Her?",
    42: "Final Boss (Nightmare's Battle)",
    43: "The Aloof Soldier",
    44: "Wendy's House",
    45: "Battle Against a Dangerous Foe",
    46: "Big Snowman",
    47: "Pika Cup Battles 1-3",
    48: "Ashley's Theme",
    49: "Silver Mountain",
    50: "Wizpig Challenge",
    51: "Talent Studio Medley",
    52: "Battle C1",
    54: "Credits (Brawl)"
}

VANILLA_MUSIC = {
    0: "Dream Land",
    1: "Planet Zebes",
    2: "Mushroom Kingdom",
    3: "Mushroom Kingdom Fast",
    4: "Sector Z",
    5: "Congo Jungle",
    6: "Peachs Castle",
    7: "Saffron City",
    8: "Yoshis Island",
    9: "Hyrule Castle",
    23: "Master Hand 0",
    24: "Master Hand 1",
    25: "Master Hand 2",
    25: "Final Destination",
    34: "How To Play",
    34: "Tutorial",
    34: "Kirby Beta 1",
    36: "Fight Polygon Stage",
    36: "Duel Zone",
    37: "Metal Mario",
    37: "Meta Crystal"
}

GAME_STATES = {
    1: "Menu",
    7: "Menu", 
    9: "Menu", 
    16: "Choosing Character",
    21: "Choosing Stage",
    22: "In Game",
    24: "Results"
}
